# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qP2uyKNr1Pd4zWcIYbxyfzynpkN5Gm8
"""

import streamlit as st
import numpy as np

st.write("""
# Two Numbler Multiplication App

This app multiplies two number
""")

st.header('User Input Parameters')

def user_input_features():
    n1 = st.number_input("Input Number_1")
    n2 = st.number_input("Input Number_2")

    return n1, n2

n1, n2 = user_input_features()
if st.button('Calculate')
    st.write(n1*n2)